act_name: elu
actor_batch_norm: false
actor_critic_step: null
actor_lr: 0.0005
actor_steps: null
agg_type: mean
algo: contrast
batch_size: 16
channel_mode: exp-32
connect_bdd: false
consistency_coef: 1.0
contrastive_rel_coef: 0.0
data_dropout: None
data_noise_amp: 0.0
dataset: mppde1d-E2-50
dataset_split_type: standard
date_time: '2022-11-21'
debug: false
decoder_act_name: None
decoder_last_act_name: linear
decoder_type: cnn-tr
density_coef: 0.001
device: !!python/object/apply:torch.device
- cpu
disc_coef: 0
disc_iters: 5
disc_loss_type: hinge
disc_lr: 0.001
disc_mode: Siamese-2
disc_reg_type: snn
disc_t: None
dp_mode: None
dropout: 0.0
early_stopping_patience: -1
encoder_mode: dense
encoder_n_linear_layers: 0
encoder_type: cnn-s
epochs: 5
epochs_pretrain: 0
epsilon_latent_loss: 0
evl_stop_gradient: false
evo_conv_type: cnn
evo_groups: 1
evo_inte_dims: -1
evo_pos_dims: -1
evolution_steps: null
evolution_type: mlp-3-elu-2
exclude_bdd: false
exp_id: le-pde-1d
fine_tune_gt_input: false
fix_alt_evolution_model: false
forward_type: Euler
gnn_mlp_n_layers: 2
gnn_mlp_n_neurons: 64
gpuid: 'False'
hinge: 0.0
id: '0'
input_steps: 1
input_steps_lazy: false
is_1d_periodic: false
is_alternating_train: false
is_clip_grad: false
is_eval_sample: true
is_latent_flatten: true
is_mesh: false
is_multistep_detach: false
is_normalize_pos: true
is_pos_transform: true
is_pretrain_autoencode: false
is_prioritized_dropout: false
is_reg_anneal: true
is_single_action: false
is_tensorboard: false
is_test_only: false
is_timing: 0
is_unittest: true
is_y_diff: false
is_y_variable_length: false
kaction_pooling_type: global_mean_pool
kernel_size: 4
latent_loss_normalize_mode: targetindi
latent_multi_step: 1*2*3*4
latent_noise_amp: 1.0e-05
latent_size: 128
layer_type: graphsage
load_dirname: None
load_exp_renew: false
load_filename: None
load_hash: None
loss_type: rmse
loss_type_consistency: mse
lr: 0.001
lr_min_cos: 0
lr_scheduler_T0: 0
lr_scheduler_T_mult: 1
lr_scheduler_factor: 0.1
lr_scheduler_type: cos
max_action: 5
max_grad_norm: -1
multi_step: 1*2*3*4
multi_step_start_epoch: 0
n_conv_blocks: 4
n_conv_layers_latent: 3
n_latent_levs: 1
n_layers: 3
n_train: '-1'
n_workers: 0
no_latent_evo: false
normalization_type: gn
offset_coarse: 0.0
offset_split: 0.0
opt: adam
opt_evl_horizon: -1
output_padding_str: 1-0-1-0
padding: 1
padding_mode: zeros
policy_input_feature: velocity
processor_aggr: max
recons_coef: 1.0
reg_coef: 0
reg_type: None
reward_beta: '0.5'
reward_condition: false
reward_loss_coef: 5
reward_mode: lossdiff+statediff
reward_src: env
rl_coefs: None
rl_critic_update_iterations: 100
rl_data_dropout: None
rl_eta: 0.0001
rl_finetune_evalution_mode: null
rl_gamma: 0.99
rl_horizon: 4
rl_is_alt_remeshing: false
rl_is_finetune_evolution: false
rl_lambda: 0.95
rl_rho: 1.0
save_interval: 2
save_iterations: 100
sector_size: '-1'
sector_stride: '-1'
seed: 0
share_processor: true
skip_coarse: false
skip_flip: false
skip_split: false
soft_update: false
static_encoder_type: param-0
static_latent_size: 3
stop_all_gradient: true
stride: 2
synch: false
temporal_bundle_steps: 25
test_data_interp: false
test_interval: 1
test_reward_random_sample: false
test_value_model: false
time_interval: 1
top_k_action: 1
train_fraction: 0.8888888888888888
unet_fmaps: 64
use_grads: false
use_pos: false
use_reward_vanilla: false
vae_beta: 1
vae_mode: None
val_batch_size: 16
value_act_name: elu
value_act_name_final: linear
value_batch_norm: false
value_latent_size: 32
value_layer_norm: false
value_loss_coef: 0.5
value_loss_type: mse
value_lr: 0.0001
value_num_pool: 1
value_num_steps: 3
value_pooling_type: global_mean_pool
value_steps: null
value_target_mode: value-lambda
verbose: 1
wandb: false
wandb_project_name: test
wandb_step: 20
wandb_step_plot: 100
weight_decay: 0.0
zero_weight: 1
